nodeLinker: node-modules

packageExtensions:
  "allotment@*":
    dependencies:
      react: "19.1.1"
      react-dom: "19.1.1"

  "react-popper@*":
    dependencies:
      react: "19.1.1"
      react-dom: "19.1.1"

  "pretty-format@*":
    dependencies:
      react: "19.1.1"

  "use-resize-observer@*":
    dependencies:
      react: "19.1.1"
      react-dom: "19.1.1"

